spring:
  application:
    name: tcc-project
  datasource:
    url: jdbc:sqlite:./tcc_project.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

google:
  vision:
    api-key: ${GOOGLE_VISION_API_KEY:}
  gemini:
    api-key: ${GEMINI_API_KEY:}
    model: ${GEMINI_MODEL:gemini-1.5-flash}
